### ISSUE TITLE
Samples, Demos, Examples

### ISSUE THREAD

**Issue by rt974** [hutts24/Blah#1]
Hi,

do you have any sample code that shows the full process.

engine initialization, scene creation, main loop, ressources loading for example ?

**Comment by hutts24** [comment]
Hi, yes I do.  I have a bogus Asteroids style game that I made to test the engine features.  It used to fly on my old nVidia Geforce2 GTS many years ago, but it is super low on modern hardware now because drivers are super optimised for drawing loads of triangles and my engine is not.

I wanted to rework the engine for drawing many triangles at once and therefore eliminating many calls to glBegin() and glEnd() before uploading the demo game.  I'll have a look today and see what I can do.

**Comment by hutts24** [comment]
I have uploaded a dodgy test/demo game in the 'GLasteroids' repository.

I worked out the engine was binding the default texture every time it drew an untextured polygon.  This was slowing things down a lot.  I've fixed that now.  There is still loads more optimisation that could be done but it's a good start.
